name: flutter_app
description: "DigiSocialMe - Unified Social Media Management Platform"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  provider: ^6.1.1

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0

  # Charts and Analytics
  fl_chart: ^0.66.1
  syncfusion_flutter_charts: ^24.1.47

  # Network and API
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  # Utils
  intl: ^0.19.0
  timeago: ^3.6.0
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  file_picker: ^6.1.1

  # Social Media Integration
  flutter_facebook_auth: ^6.0.4
  twitter_login: ^4.4.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
